# -*- coding: utf-8 -*-
"""Listado de revision de los Planes de Control Rev 0 (APB de puerta e Insert Patagonia)
que mando Nicolas Perez el 30/09/2026. Sale del cruce del 01/10/2026 contra flujograma,
AMFE (Supabase live), hojas de operaciones y BOM del arb.

    python scripts/scratch/_listadoRevisionPcPuertas.py <salida.xlsx>
"""
import sys
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

CAL, ING, DEF = "Calidad", "Ingeniería", "A definir juntos"

COLS = ["N°", "Operación", "Fila del PC", "Qué dice hoy el PC",
        "Qué dicen los documentos de Ingeniería", "Qué falta", "Quién"]
ANCHOS = [5, 22, 9, 44, 58, 44, 13]

APB = [
    ("General", "encab.",
     "N° de parte, N° de plan, código de cliente y fecha de revisión vacíos. Dice \"APOYABRAZOS\" y quedó \"INCLUIR DETALLE\". Característica S/R con las dos casillas marcadas.",
     "Piezas: N 231 / N 267 / N 297 / N 328 (APB de puerta delantero y trasero, Patagonia, NOVAX).",
     "Completar el encabezado con los 4 códigos.", CAL),
    ("General", "todas",
     "La columna \"Clasif. carac. espec.\" está vacía en todas las filas.",
     "Flujograma 153 Rev.C y AMFE 161: D/TLD y SC en la operación 10; SC en 20, 21, 30, 40, 41, 50, 70, 71, 80-82 y 100.",
     "Volcar las siglas del AMFE 161. Ingeniería pasa el listado causa por causa.", CAL),
    ("General", "114-118",
     "Una sola \"Operación 20\" que junta la preparación, el corte y el control.",
     "Flujograma 153 Rev.C: 20 PREPARACIÓN Y CARGA DE VINILO · 21 CORTE AUTOMÁTICO DE COMPONENTES · 22 CONTROL CON MYLAR.",
     "Separar en 20, 21 y 22 con la numeración del flujograma.", CAL),
    ("General", "-",
     "No tiene fila para las operaciones 51, 71, 100 y 101. El embalaje no tiene número.",
     "Flujograma 153 Rev.C: 51 CONTROL DE PIEZA INYECTADA · 71 INSPECCIÓN DE PIEZA ADHESIVADA · 100 REPROCESO: FALTA DE ADHESIVO · 101 REPROCESO: REACTIVACIÓN DE ADHESIVO POR CALOR · 110 EMBALAJE.",
     "Agregar las 4 operaciones y numerar el embalaje como 110. Los controles de la 51 hoy están dentro de la 50.", CAL),
    ("General", "-",
     "El libro trae una \"Hoja2\" con números sueltos sin título.",
     "-", "Sacarla o aclarar qué es.", CAL),
    ("10 Recepción", "77-81",
     "Vinilo con código 427-VIN-009 / COR-01. Espesor y gramaje sin valor.",
     "BOM del arb (28/09/2026): VIN-SKM-001, vinilo PVC Texture PR022.",
     "Unificar el código con el de la BOM. Espesor y gramaje: ningún documento de Ingeniería los trae; salen de la ficha del proveedor.", DEF),
    ("10 Recepción", "82-87",
     "Hilo de unión 427-HIL-001 e hilo de costura \"Carbon Black 427 HIL-005-COS-01\".",
     "BOM del arb: hilo de unión FX284-E0PTO (30/3) e hilo de costura vista FX483TK-E0PTO, Jet Black 20/3.",
     "Unificar código y color con la BOM.", CAL),
    ("10 Recepción", "82-87",
     "Los hilos no tienen fila de flamabilidad. El vinilo no tiene fila de lote.",
     "AMFE 161, operación 10: flamabilidad de vinilo, hilo de unión e hilo de costura con D/TLD; trazabilidad de lote del vinilo.",
     "Agregar flamabilidad de los dos hilos y lote del vinilo.", CAL),
    ("10 Recepción", "109-112",
     "El código de la grampa está escrito de dos formas: DK/1840400 y DK840400.",
     "BOM del arb: DK/1840400, grampa DK 84-04 (4 mm).",
     "Dejar DK/1840400.", CAL),
    ("10 Recepción", "-",
     "No figuran las etiquetas.",
     "BOM del arb: ET-SATO-50X20 (1 por pieza) y ET-SATO-100X60.",
     "Agregarlas a recepción o aclarar que no se controlan.", CAL),
    ("10 Recepción", "91-93",
     "Film Tesa 52110 en recepción.",
     "Está en la BOM. Ninguna hoja de operación dice dónde se aplica.",
     "Ingeniería confirma en qué operación se usa.", ING),
    ("20-21 Corte", "114",
     "Medida de cuchilla 5 - 8 mm, calibre MC213.",
     "HO 971, operación de medición de cuchilla: ancho de cuchilla 4 mm mínimo, calibre MC167, antes de cada corte.",
     "Definir cuál de las dos medidas y cuál calibre vale.", DEF),
    ("21 Corte", "-",
     "No controla el código de material antes de cortar.",
     "AMFE 161 operación 21 (prioridad alta): verificar el código del vinilo contra la planilla de mesa de corte. La HO 971 lo controla en cada rollo.",
     "Agregar la fila.", CAL),
    ("22 Control con Mylar", "115",
     "\"Corte de pliegos a medidas correctas\" con plantilla de control, sin tolerancia.",
     "HO 971: contorno de la pieza dentro de la plantilla Mylar, tolerancia ±1 mm.",
     "Pasar a la operación 22 con la tolerancia.", CAL),
    ("30 Refilado", "119-120",
     "El set up tiene texto de máquina de coser (aceite, hilo, crochet). Máquina \"( )\" sin completar.",
     "El refilado no usa máquina de coser.",
     "Corregir el set up y completar la máquina.", CAL),
    ("40 Costura unión", "121-139",
     "Dice \"Apoyabrazos delantero\".",
     "Flujograma y HO 971: la operación 40 aplica a los 4 códigos.",
     "Sacar \"delantero\".", CAL),
    ("40 Costura unión", "134",
     "Atraque: 2 x 3 puntadas.",
     "HO 971 operación 40: atraque de 3 a 4 puntadas al inicio y al final.",
     "Definir cuál vale.", DEF),
    ("40 Costura unión", "136-139",
     "Margen de costura y largo de puntada sin valor. N° de aguja sin valor.",
     "Largo de puntada: 4 puntadas en 16 mm ±1 (HO 971 y especificación de costura del cliente del 28/08/2025). Margen: Ingeniería lo confirma. N° de aguja: no está en ningún documento.",
     "Completar el largo de puntada. Margen y aguja quedan a confirmar.", ING),
    ("41 Costura vista", "147-148",
     "\"Paralelismo entre costuras cara vista\".",
     "Flujograma y HO 971: la costura vista es de 1 sola línea.",
     "Sacar la fila.", CAL),
    ("41 Costura vista", "151-152",
     "Margen de 8 ±1 mm.",
     "HO 971 operación 41 y especificación de costura del cliente: 4 mm ±1.",
     "Corregir a 4 mm ±1.", CAL),
    ("41 Costura vista", "153-154",
     "Largo de puntada 4 mm (6 puntadas por pulgada).",
     "Especificación de costura del cliente: 4 puntadas en 16 mm ±1.",
     "Ingeniería confirma cómo se expresa.", ING),
    ("41 Costura vista", "157-158",
     "Solo figura el hilo de aguja.",
     "HO 971 operación 41: aguja 20/3 y bobina 30/3.",
     "Agregar la bobina.", CAL),
    ("50-51 Inyección plástica", "160-161",
     "Peso sin valor.",
     "HO 971, control de pieza inyectada: delantero 120 ±5 g · trasero 115 ±5 g, con balanza.",
     "Completar.", CAL),
    ("50-51 Inyección plástica", "165",
     "\"Controlar dimensional cotas\", sin cotas.",
     "HO 971: cota index delantero 214 ±1 mm · trasero 173,5 ±1 mm, medida a los 20 minutos de inyectada.",
     "Completar.", CAL),
    ("50-51 Inyección plástica", "159",
     "Parámetros: \"Ver hoja de set up\".",
     "AMFE 161 operación 50: temperatura de fusión, presión de inyección y fuerza de cierre con SC. La HO 971 no trae los valores.",
     "Falta la hoja de parámetros de la inyectora con valores.", DEF),
    ("50-51 Inyección plástica", "162-163",
     "Aspecto: 1 pieza al inicio y fin de turno y 1 por lote.",
     "AMFE 161 operación 50: inspección visual al 100 %.",
     "Revisar la frecuencia.", DEF),
    ("60 Inyección PU", "167-177",
     "9 parámetros sin valor (temperatura de molde, tiempos, caudal, relación, presiones) y peso \"?\".",
     "Ningún documento trae los valores. La hoja de esta operación está sin terminar.",
     "Hay que relevar los parámetros de la inyectora de PU y el peso de la pieza.", DEF),
    ("70 Adhesivado", "185",
     "Temperatura de hotmelera sin valor.",
     "HO 971 operación 70: temperatura de la máquina entre 190 y 210 °C.",
     "Completar.", CAL),
    ("70 Adhesivado", "184-190",
     "Adhesivado con hotmelera y rodillo.",
     "Coincide con la HO 971 y con la BOM (un solo adhesivo, HB Fuller CQ-7080-5). La operación 70 del AMFE 161 está en revisión.",
     "Ingeniería actualiza la operación 70 del AMFE 161 y después pasa sus siglas.", ING),
    ("70 Adhesivado", "186-188",
     "Velocidad del rodillo, cantidad de carga y altura de rodillo sin valor.",
     "Ningún documento trae los valores.",
     "Relevar en la máquina.", DEF),
    ("71 Inspección de pieza adhesivada", "-",
     "No existe la operación.",
     "Flujograma, AMFE 161 y HO 971 la tienen (SC). El peso del vinilo adhesivado está sin definir.",
     "Agregar la operación. El peso queda a definir.", DEF),
    ("80-82 Tapizado", "192",
     "Fila con número y sin contenido.",
     "-", "Completar o sacar.", CAL),
    ("80-82 Tapizado", "193-196",
     "Grampas: 27 delantero / 21 trasero, de 4 mm.",
     "Coincide con la BOM del arb del 28/09 y con las hojas de engrampado y los caminos de inspección de grampas.",
     "Citar el camino de inspección de grampas como método de control. La presión de aire de la engrampadora no tiene valor. Ingeniería confirma el número de operación del engrampado.", DEF),
    ("90 Control final", "208",
     "Largo de puntada 4 mm (4 puntadas 16 ±1 mm).",
     "Es el valor de las dos costuras según la especificación del cliente.",
     "Sin cambios.", CAL),
    ("90 Control final", "209-210",
     "\"Prueba en calibre de control según instructivo\" y \"sello WQ\".",
     "No figuran en ningún documento de Ingeniería.",
     "Aclarar qué calibre, qué instructivo y qué es el sello.", CAL),
    ("110 Embalaje", "211",
     "\"Embalaje final\": TBD.",
     "HO 971 operación 110: caja de cartón 420 x 540 x 300 mm con divisores, 24 piezas por caja, 4 cajas por piso.",
     "Completar.", CAL),
    ("Varias", "167-175 / 185-188",
     "Temperaturas, presiones y velocidades con técnica \"Control visual\" y cargadas en la columna PRODUCTO.",
     "-", "Pasarlas a la columna PROCESO con el instrumento o la pantalla donde se leen.", CAL),
]

INSERT = [
    ("General", "encab.",
     "N° de parte, N° de plan, código de cliente y fecha de revisión vacíos. Dice \"INSERTOS\" y quedó \"INCLUIR DETALLE\".",
     "Piezas: N 227 y N 389 a N 403 (16 códigos).",
     "Completar el encabezado con los códigos.", CAL),
    ("General", "todas",
     "La columna \"Clasif. carac. espec.\" está vacía en todas las filas.",
     "Flujograma 154 Rev.C y AMFE 158: D/TLD y SC en la operación 10; SC en 20, 21, 22, 50, 60, 71, 90, 91, 93, 100, 101, 102 y 110.",
     "Volcar las siglas del AMFE 158. Ingeniería pasa el listado causa por causa.", CAL),
    ("General", "127-131",
     "Una sola \"Operación 20\" con el nombre CORTAR COMPONENTES.",
     "Flujograma 154 Rev.C: 20 PREPARACIÓN DE CORTE · 21 CORTAR COMPONENTES · 22 CONTROL CON MYLAR.",
     "Separar en 20, 21 y 22.", CAL),
    ("General", "-",
     "No tiene las operaciones 91 y 93.",
     "Flujograma 154 Rev.C: 91 INSPECCIÓN DE PIEZA ADHESIVADA · 93 REPROCESO: FALTA DE ADHESIVO, las dos con SC.",
     "Agregarlas. Los controles de aspecto de la 91 hoy están dentro de la 90.", CAL),
    ("General", "155-161",
     "\"Operación 70-71\" junta.",
     "Flujograma 154 Rev.C: 70 INYECCIÓN DE PIEZAS PLÁSTICAS · 71 CONTROL DE PIEZA INYECTADA.",
     "Separar en 70 y 71.", CAL),
    ("10 Recepción", "77-96",
     "Los 4 vinilos no tienen código. Espesor y gramaje sin valor.",
     "BOM del arb (28/09/2026): 1246030226 (S085 negro) · 1246030225 (S704) · 1246030223 (S782) · 1246030224 (ML14 S769), todos Sanleather IV 1,1 x 1400 con espuma de 3,00.",
     "Agregar los códigos. Gramaje y tolerancia de espesor: salen de la ficha del proveedor.", DEF),
    ("10 Recepción", "97-105",
     "Los 3 hilos de costura vista, sin fila de flamabilidad.",
     "AMFE 158 operación 10: flamabilidad del hilo con D/TLD.",
     "Agregar flamabilidad.", CAL),
    ("10 Recepción", "-",
     "No figura el hilo de unión.",
     "BOM del arb y AMFE 158: hilo de unión FX284-E0PTO (30/3) en los 16 códigos, con flamabilidad D/TLD.",
     "Agregar el hilo de unión con su flamabilidad.", CAL),
    ("10 Recepción", "109-111",
     "Espuma: espesor TBD y densidad TBD.",
     "BOM del arb: espuma de PU de densidad 35 kg/m3.",
     "Completar la densidad. El espesor y su tolerancia salen de la ficha del proveedor.", CAL),
    ("10 Recepción", "122-125",
     "Grampa con código DK/1840400 (y DK840400) y alto 6 mm.",
     "BOM del arb (28/09/2026): DK/1840600, grampa Dorking 84/06 (6 mm).",
     "Corregir el código a DK/1840600.", CAL),
    ("10 Recepción", "120-121",
     "\"Sustrato plástico MG47 (22020541)\".",
     "En la BOM el 22020541 es la resina MG47 BK1066. El sustrato se inyecta en planta en la operación 70.",
     "Tratarlo como resina.", CAL),
    ("10 Recepción", "-",
     "Vinilo, hilos y espuma sin fila de lote. Sin control del estado del embalaje.",
     "AMFE 158 operación 10 y HO-990: trazabilidad de lote y estado del embalaje al recibir.",
     "Agregar.", CAL),
    ("21 Corte", "127",
     "Medida de cuchilla 5 - 8 mm, calibre MC213.",
     "HO-990 operación 21: ancho de cuchilla 4 mm mínimo, calibre MC167, antes de cada corte.",
     "Definir cuál de las dos medidas y cuál calibre vale.", DEF),
    ("21 Corte", "130",
     "Cantidad de capas: 5.",
     "No figura en ningún documento de Ingeniería.",
     "Confirmar de dónde sale el 5.", DEF),
    ("20-21 Corte", "-",
     "No controla el código y el color del vinilo antes de cortar.",
     "AMFE 158 (prioridad alta) y HO-990 operación 20: código y color del vinilo, en el 100 % de los rollos.",
     "Agregar la fila.", CAL),
    ("22 Control con Mylar", "131",
     "\"Según Myler\", sin tolerancia.",
     "HO-990 operación 22: contorno ±1 mm con plantilla Mylar, al inicio de turno y en cada cambio de lote.",
     "Pasar a la operación 22 con la tolerancia.", CAL),
    ("50 Costura CNC", "133",
     "Máquina: \"costura recta N° BM\".",
     "Flujograma, AMFE y HO-990: costura en máquina CNC.",
     "Corregir la máquina.", CAL),
    ("50 Costura CNC", "141-150",
     "N° de aguja, margen de costura y largo de puntada sin valor. Atraque 2 x 3 puntadas.",
     "No figuran en los documentos de Ingeniería del Insert.",
     "Ingeniería define los valores de costura del Insert.", ING),
    ("50 Costura CNC", "133-140",
     "Aspecto de costura: 1 pieza al inicio y fin de turno y 1 por lote.",
     "HO-990 operación 50: costura y paso de puntada, visual al 100 % de las piezas.",
     "Revisar la frecuencia.", DEF),
    ("50 Costura CNC", "-",
     "No controla el programa de costura ni la tensión del hilo.",
     "AMFE 158 operación 50 (prioridad alta): programa contra la plantilla física, tensión de hilo, presión de aire.",
     "Agregar.", CAL),
    ("60 Troquelado", "152",
     "Parámetro de troqueladora sin valor.",
     "Ningún documento trae los valores.",
     "Relevar en la máquina.", DEF),
    ("70-71 Inyección", "156-161",
     "Peso sin valor. \"Controlar dimensional cotas\" sin cotas.",
     "No hay valores en los documentos de Ingeniería del Insert. La HO-990 pide el dimensional en calibre cada 2 horas.",
     "Ingeniería define peso y cotas. Revisar la frecuencia.", ING),
    ("70-71 Inyección", "155-156 (col. O)",
     "Texto suelto fuera de la tabla: \"Carbon Black (código 427 HIL-005-COS-01)\".",
     "No es del Insert.", "Borrar.", CAL),
    ("90 Adhesivado", "172-179",
     "Filas \"Peso ?\", \"Sin falta de llenado\", \"Sin roturas\" y \"Canaleta de costura completa\".",
     "Son controles de inyección de PU del apoyabrazos. El Insert no lleva PU.",
     "Sacar las filas.", CAL),
    ("90 Adhesivado", "165-171",
     "Adhesivo FA con reticulante GV, aplicado sobre el sustrato.",
     "Coincide con la BOM y con el AMFE 158. La hoja de la operación 90 de la HO-990 está en revisión.",
     "Sin cambios en el PC. Ingeniería actualiza la hoja.", ING),
    ("90 Adhesivado", "166",
     "Adhesivo: máximo 6 meses desde la recepción.",
     "Recepción (fila 114) dice \"menos de 179 días\" según certificado.",
     "Dejar un solo criterio de vencimiento.", CAL),
    ("90 Adhesivado", "167",
     "Mezcla: una botella de reticulante GV en un tacho de adhesivo FA.",
     "Coincide con la BOM. La vida útil de la mezcla no está en ningún documento.",
     "Definir la vida útil de la mezcla.", DEF),
    ("100 Tapizado", "181-185",
     "Filas 2 y 3 vacías.",
     "HO-990 operación 100: tiempos y vacío de la máquina; temperatura de vinilo y sustrato con termómetro infrarrojo cada 2 horas. Ningún documento trae los valores.",
     "Agregar las características. Los valores hay que relevarlos.", DEF),
    ("100 Tapizado", "-",
     "No controla que la costura asiente en la canaleta.",
     "AMFE 158 y HO-990 operación 100: alineación de la costura en la canaleta, visual al 100 %.",
     "Agregar.", CAL),
    ("101 Virolado manual", "191-193",
     "Tres filas sin característica. Máquina: \"Operador de producción\".",
     "HO-990 operación 101: engrampadora neumática y pistola de calor; bordes lisos y pegados, sin hundimientos en la cara vista.",
     "Completar.", CAL),
    ("101 Virolado manual", "194-197",
     "Grampas: 36 delantero / 23 trasero, de 6 mm.",
     "Coincide con la BOM del arb del 28/09 y con los caminos de inspección de grampas.",
     "Citar el camino de inspección de grampas como método de control.", CAL),
    ("102 Refilado", "200-201",
     "Control \"por lote\". Máquina: \"operador de producción\".",
     "HO-990 operación 102: contorno contra patrón al inicio de turno y en cada lote; estado de la hoja del cutter.",
     "Agregar el estado del cutter y ajustar la frecuencia.", CAL),
    ("110 Control final", "202-207",
     "Aspecto: 1 por lote.",
     "HO-990 y AMFE 158 operación 110: inspección al 100 %, con adherencia del perímetro y de los bordes.",
     "Agregar la adherencia del perímetro y revisar la frecuencia.", DEF),
    ("110 Control final", "208-209",
     "\"Prueba en calibre de control según instructivo\" y \"sello WQ\".",
     "No figuran en ningún documento de Ingeniería.",
     "Aclarar qué calibre, qué instructivo y qué es el sello.", CAL),
    ("120 Embalaje", "210",
     "\"Embalaje final\": TBD.",
     "La cantidad por caja de la pieza terminada no está definida en una hoja vigente.",
     "Definir con la ficha de embalaje.", DEF),
]

TOPROLL = [
    ("General", "encab.",
     "N° de parte, N° de plan, código de cliente y fecha de revisión vacíos. Dice \"TOP ROLL\" y quedó \"INCLUIR DETALLE\".",
     "Piezas: N 216 / N 256 (delanteros) y N 285 / N 315 (traseros).",
     "Completar el encabezado con los 4 códigos.", CAL),
    ("General", "todas",
     "La columna \"Clasif. carac. espec.\" está vacía (salvo dos textos corridos en las filas 126 y 127).",
     "Flujograma 155 Rev.C y AMFE 162: D/TLD y SC en la operación 5; SC en 10, 50 y 80.",
     "Volcar las siglas del AMFE 162. Ingeniería pasa el listado causa por causa.", CAL),
    ("General", "125-131",
     "La operación 60 es la soldadura de tweeter y la 70 la soldadura de refuerzos.",
     "Flujograma 155 Rev.C y AMFE 162: 60 SOLDADURA POR ULTRASONIDO DE REFUERZOS · 70 SOLDADURA POR ULTRASONIDO DE TWEETER.",
     "Invertir los números.", CAL),
    ("General", "-",
     "No tiene la operación 40.",
     "Flujograma 155 Rev.C y AMFE 162: 40 TRIMMING CORTE FINAL.",
     "Agregarla.", CAL),
    ("General", "96-97 (col. O)",
     "Texto suelto fuera de la tabla: \"Carbon Black (código 427 HIL-005-COS-01)\".",
     "No es del Top Roll.", "Borrar.", CAL),
    ("5 Recepción", "77-81",
     "TPO: espesor, ancho del rollo y gramaje sin valor.",
     "BOM del arb (28/09/2026): 427VIN005COR01, TPO 0,5 mm + espuma 2 mm.",
     "Los valores salen de la ficha del proveedor.", DEF),
    ("5 Recepción", "89-90",
     "\"Tweeter ABS negro (código INY-TRL0009-V1)\".",
     "La BOM del arb no tiene ese código. Los traseros (N 285 y N 315) llevan REJILLA ALTAVOZ TRASERO 2HC.868.184 / 2HC.868.183.",
     "Ingeniería confirma la pieza y su código, y actualiza el AMFE 162.", ING),
    ("5 Recepción", "84-85",
     "\"Refuerzo interno termoplástico MG47 (22020541)\".",
     "En la BOM el 22020541 es la resina MG47 BK1066 con la que se inyecta el refuerzo en planta.",
     "Tratarlo como resina.", CAL),
    ("5 Recepción", "91-94",
     "El código de la grampa está escrito de dos formas: DK/1840400 y DK840400.",
     "BOM del arb: DK/1840400, grampa DK 84-04 (4 mm).",
     "Dejar DK/1840400.", CAL),
    ("5 Recepción", "-",
     "No figuran las etiquetas.",
     "BOM del arb: ET-SATO-50X20 (2 por pieza) y ET-SATO-100X60.",
     "Agregarlas a recepción o aclarar que no se controlan.", CAL),
    ("10 Inyección", "97-102",
     "Peso sin valor. \"Controlar dimensional cotas\" sin cotas.",
     "El AMFE 162 pide el control de peso y de cotas; los valores no están en una hoja vigente.",
     "Ingeniería define peso y cotas.", ING),
    ("20 Adhesivado hot melt", "104-106",
     "Carga de rollo, velocidad de máquina y cantidad de carga de hot melt, sin valor.",
     "Receta de la máquina leída en pantalla: velocidad de línea 3,0 m/min, rodillos a 185 °C (alarma a ±10 °C), luz entre rodillos 0,250 mm. Fusor de adhesivo a 160 °C.",
     "Completar la velocidad y agregar temperatura de rodillos, temperatura del fusor y luz entre rodillos.", CAL),
    ("20 Adhesivado hot melt", "-",
     "No tiene control de adherencia ni de cantidad de adhesivo.",
     "AMFE 162 operación 20: ensayo de adherencia por lote y control del peso de adhesivo por metro cuadrado. No hay método ni valor definidos.",
     "Definir método, valor y frecuencia.", DEF),
    ("30 Termoformado IMG", "110-112",
     "Filas 2 y 3 vacías. Sin parámetros de máquina.",
     "Las hojas de proceso de la moldeadora IMG todavía no traen valores de proceso.",
     "Relevar los parámetros en la máquina.", DEF),
    ("50 Plegado de bordes", "120-124",
     "Tres filas vacías. No figura el engrampado.",
     "BOM del arb y caminos de inspección de grampas: 27 grampas en el delantero y 34 en el trasero, de 4 mm.",
     "Agregar cantidad y tamaño de grampa, con el camino de inspección como método. Ingeniería actualiza la operación 50 en flujograma y AMFE.", DEF),
    ("60 (PC) Soldadura de tweeter", "126-127",
     "\"Refilar bordes excedentes de vinilo de la pieza terminada\" y \"Ver patrón de refilado\".",
     "Son textos de un refilado; no corresponden a una soldadura.",
     "Corregir las dos filas.", CAL),
    ("80 Control final", "135",
     "\"Cantidad de grampas ok\", sin cantidad.",
     "27 delantero / 34 trasero.",
     "Agregar la cantidad.", CAL),
    ("80 Control final", "138-139",
     "\"Prueba en calibre de control según instructivo\" y \"sello WQ\".",
     "No figuran en ningún documento de Ingeniería.",
     "Aclarar qué calibre, qué instructivo y qué es el sello.", CAL),
    ("90 Embalaje", "140",
     "\"Embalaje final\": TBD.",
     "La cantidad por caja no está definida en una hoja vigente.",
     "Definir con la ficha de embalaje.", DEF),
]


def hoja(wb, titulo, sub, filas, primera=False):
    ws = wb.active if primera else wb.create_sheet()
    ws.title = titulo
    fino = Side(style="thin", color="999999")
    borde = Border(left=fino, right=fino, top=fino, bottom=fino)
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(COLS))
    ws["A1"] = sub
    ws["A1"].font = Font(bold=True, size=13)
    ws["A1"].alignment = Alignment(vertical="center")
    ws.row_dimensions[1].height = 26
    for j, c in enumerate(COLS, 1):
        cel = ws.cell(row=2, column=j, value=c)
        cel.font = Font(bold=True, color="FFFFFF")
        cel.fill = PatternFill("solid", fgColor="1F3864")
        cel.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cel.border = borde
        ws.column_dimensions[get_column_letter(j)].width = ANCHOS[j - 1]
    ws.row_dimensions[2].height = 22
    color = {CAL: "FFFFFF", ING: "DDEBF7", DEF: "FFF2CC"}
    for i, (op, fila, pc, ing, falta, quien) in enumerate(filas, 1):
        r = i + 2
        vals = [i, op, fila, pc, ing, falta, quien]
        largo = 0
        for j, v in enumerate(vals, 1):
            cel = ws.cell(row=r, column=j, value=v)
            cel.alignment = Alignment(vertical="top", wrap_text=True,
                                      horizontal="center" if j in (1, 3, 7) else "left")
            cel.border = borde
            cel.fill = PatternFill("solid", fgColor=color[quien])
            if j in (4, 5, 6):
                largo = max(largo, len(str(v)) / (ANCHOS[j - 1] * 1.05))
        ws.row_dimensions[r].height = max(30, 15 * (int(largo) + 1))
    ws.freeze_panes = "A3"
    ws.page_setup.orientation = "landscape"
    ws.page_setup.paperSize = ws.PAPERSIZE_A4
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 0
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.print_title_rows = "1:2"
    ws.page_margins.left = ws.page_margins.right = 0.3
    ws.page_margins.top = ws.page_margins.bottom = 0.4
    return ws


def main():
    out = sys.argv[1]
    wb = Workbook()
    hoja(wb, "APB de puerta",
         "Plan de Control APB de puerta Patagonia, Rev 0 (25/09/2026). Revisión de Ingeniería del 01/10/2026",
         APB, primera=True)
    hoja(wb, "Insert",
         "Plan de Control Insert Patagonia, Rev 0 (25/09/2026). Revisión de Ingeniería del 01/10/2026",
         INSERT)
    hoja(wb, "Top Roll",
         "Plan de Control Top Roll Patagonia, Rev 0 (25/09/2026). Revisión de Ingeniería del 01/10/2026",
         TOPROLL)
    wb.save(out)
    n = {CAL: 0, ING: 0, DEF: 0}
    for lista in (APB, INSERT, TOPROLL):
        for f in lista:
            n[f[5]] += 1
    print("APB", len(APB), "· Insert", len(INSERT), "· Top Roll", len(TOPROLL), "·", n)


if __name__ == "__main__":
    main()
